version: '3.7'

services:
  node:
    image: node:20.11.0
    user: '1000:1000'
    volumes:
      - ./:/app/
      - ./.docker/linux/.bashrc:/home/node/.bashrc
    ports:
      - 4000:4000
    working_dir: /app/
    command: bash -c "npm install && npm run dev"
    # command: tail -F anything
